name: Context Testing

on: workflow_dispatch

jobs:
    dump_contexts_to_logs:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            fail-fast: false
        steps:
            - name: Dump Github Context
              env:
                GITHUB_CONTEXT: ${{tojson(github)}}
              run: echo "$GITHUB_CONTEXT"
            
            - name: Dump job context
              env: 
                JOB_CONTEXT: ${{tojson(job)}}
              run: echo "$JOB_CONTEXT"

            - name: Dump steps context
              env:
                STEP_CONTEXT: ${{tojson(steps)}}
              run: echo "$STEP_CONTEXT"
            
            - name: Dump runner context
              env:
                RUNNER_CONTEXT: ${{tojson(runner)}}
              run:  echo "$RUNNER_CONTEXT"

            - name: Dump strategy context
              env:
                STRATEGY_CONTEXT: ${{tojson(strategy)}}
              run:  echo "$STRATEGY_CONTEXT"

            - name: Dump matrix context
              env: 
                MATRIX_CONTEXT: ${{tojson(matrix)}}
              run:  echo "$MATRIX_CONTEXT"

            - name: Dump matrix context-02
              run:  echo "${{tojson(matrix)}}"
            
            - name: Design step-1
              run: echo "--------------------------------------------------"

            - name: Final Step!!!!!!!! :)
              run: echo ":) Thank you, this is the end of the context :)"

            - name: Design step-2
              run: echo "--------------------------------------------------"

              