name: Matrix Docker

on: 
    workflow_dispatch:

jobs:
    Docker-Matrix:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                image: [alpine, hello-world]
        steps:
            - name: Docker info
              run: docker info
            
            - name: Run docker image
              run: docker run ${{matrix.image}}