name: running shell script

on: [workflow_dispatch]

jobs:
    shell_script:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v6
            - name: executing the shell script
              run: bash ./demo.sh