name: Needs Meta Argument Example

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Job 1 Execution
        run: echo "This is Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Job 2 Execution
        run: echo "This is Job 2 and it depends on Job 1"

  job3:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Job 3 Execution
        run: echo "This is Job 3 and it also depends on Job 1"

  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]

    steps:
      - name: Job 4 Execution
        run: echo "This is Job 4 and it depends on Job 2 and Job 3"